### ISSUE TITLE
tourr version dependence

### ISSUE THREAD

**Issue by uschiLaa** [sa-lee/liminal#11]
The interface with tourr will need to be updated to work with version 0.5.7 (not yet on CRAN)

**Comment by sa-lee** [comment]
How do you mean? As in the package doesn't work on the dev version of the tourr?

**Comment by uschiLaa** [comment]
I initially had the dev version of tourr installed, this gave me an error (which might be a bug in tourr):

> limn_tour(pdfsense, PC1:PC6, Type)
Error in path(0) : object 'verbose' not found

after installing the stable tourr version from CRAN everything works ok

**Comment by sa-lee** [comment]
Has something changed internally for `new_tour()` in 0.5.7?

**Comment by sa-lee** [comment]
This is a bug in `new_tour()` in 0.5.7
https://github.com/ggobi/tourr/blob/26838bad2b4cd91f9b01f3ac5dff4c63acc3466c/R/tour.r#L54
It expects a boolean called verbose that isn't. passed in by default. 

Want me to PR?

**Comment by uschiLaa** [comment]
Yes, there is a new "verbose" argument that turns on keeping track of information as the tour is running. It is initialised in "animate" or "save_history" as a global object, so if you call new_tour directly it is not defined. Would be good to check with Sherry, so PR or issue in the tourr repo

**Comment by sa-lee** [comment]
Ok I'll add that in now. I'm kind of concerned about the amount of `<<-` with the new verbose arg. Lots of modifying the external environment  which seems unnecessary.

**Comment by sa-lee** [comment]
Ok this should work with current tour now
