### ISSUE TITLE
Problems coloring points

### ISSUE THREAD

**Issue by pfh** [sa-lee/liminal#9]
Hi Stuart,

Using `limn_tour_link` with tour_color but not embed_color seems to fail.

```
# Works
limn_tour_link(tour_data=mtcars, embed_data=select(mtcars, mpg, wt))

# Works, points are colored
limn_tour_link(tour_data=mtcars, embed_data=select(mtcars, mpg, wt, cyl), tour_color=cyl, embed_color=cyl)

# Works, embedding points are colored
limn_tour_link(tour_data=mtcars, embed_data=select(mtcars, mpg, wt, cyl), embed_color=cyl)

# App loads, but no plot appears
limn_tour_link(tour_data=mtcars, embed_data=select(mtcars, mpg, wt, cyl), tour_color=cyl)
limn_tour_link(tour_data=mtcars, embed_data=select(mtcars, mpg, wt), tour_color=cyl)
```

I also got quite confused by how `tour_color` and `embed_color` are interpreted. I think I will always want to color the points the same way in the two plots... it seems I can't just give a vector of colors from my environment, and that the color column has to be present in both data frames.

**Comment by sa-lee** [comment]
Hi Paul, good point! I agree it would be simpler just have one colour column that could be in either data.frame. Will get around to updating this on Monday :)

**Comment by sa-lee** [comment]
@pfh would you be up for meeting next Thursday to discuss some of your thoughts around the package?

**Comment by pfh** [comment]
Yes, sure. What time?

**Comment by sa-lee** [comment]
just sending you an email :)
